dist: trusty
language: node_js
node_js:
- '10.9'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable --allow-unauthenticated
  sonarcloud:
    organization: "sytw2019"
    token:
      secure: "6b62363070108fbf3c36897d6d3753704e7ac505"
cache:
  directories:
  - "./tiendaO/node_modules"
#before_install:
#- cd tiendaOnlineLogMen
install:
- npm install
notifications:
  slack: sytw:eFSSfJ93dL6SYCHkgOxiacNL
script:
- sonar-scanner
- cd tiendaO
- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
