dist: trusty
sudo: false

language: node_js
node_js:
  - '8'

cache:
  directories:
    - ./tiendaOnlineLogMen/node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
