dist: trusty

language: node_js
node_js:
  - '10.9'

cache:
  directories:
    - ./tiendaOnlineLogMen/node_modules

before_install: cd tiendaOnlineLogMen

install:
  - npm install

script:
  - npm run test
