dist: trusty
language: node_js
node_js:
- '10.9'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    sonarcloud:
      organization: "sytw2019"
    token: 
      secure: TwNfJlO6673FE4uGoYRsUlb3YqeXuH9OqAHl1fYou0P3v5Lsfvl8QsB98fXFf0iD8WBk29kTpDHNEsbliFPfnTy4FVh5uYL/+f2lFhnPv9nODDH3ViKjILGHm+zh0ZeETS/1puBZZXL1VNh9eoRYFASHSFSXFVXAsCM8USk3Ded54VAJW9sK+FKq3pPSGsXskMvrg2G2yNVsnKMYJgL295ObbQGbPtPB/EUNjWX93uwhEt4HOYUuK1PHQjogWGLKYH7bh5TZVH2GQ8b/eb8S2jpjNc0dnzDGvwGeHZdxuAdU8O1z9aj7ZBYjccgCAe397UFL92qflVJebanCU77v3Yu8EFIDxbfwuR+fpg+BOOffU/77GHlznbhb0XcHa9QyI8Cj+riQHvRf3D3t/dBTaZF7OxynPkB4awJ5qfAa5XS9GLZmwZh2YBB2qWePwvIPWiVJT0snOEPq4W16KJ3Pszy43opeanUoNrd9prbea4sgwcROJ+F8UHDOPbtR8SGgcqY7MoM315Fhes9Dyl7QqykckmH83GV+6uY953slrMOq7asLfCbfgB4j4zv448IcPmYxa6Fys8w+TBM44d+xhjvyAF6P7IZJqDekDoc8lqQK08d6OoI888p86nIXzL3QgFbJnwRAMBue/+hYfoegU1/WXY7vNo4xvZtH8IFAs+c=

cache:
  directories:
  - "./tiendaOnlineLogMen/node_modules"
before_install:
- cd tiendaOnlineLogMen
install:
- npm install
notifications:
  slack: sytw:eFSSfJ93dL6SYCHkgOxiacNL
script:
#- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
- sonar-scanner
dd:
  secure: TwNfJlO6673FE4uGoYRsUlb3YqeXuH9OqAHl1fYou0P3v5Lsfvl8QsB98fXFf0iD8WBk29kTpDHNEsbliFPfnTy4FVh5uYL/+f2lFhnPv9nODDH3ViKjILGHm+zh0ZeETS/1puBZZXL1VNh9eoRYFASHSFSXFVXAsCM8USk3Ded54VAJW9sK+FKq3pPSGsXskMvrg2G2yNVsnKMYJgL295ObbQGbPtPB/EUNjWX93uwhEt4HOYUuK1PHQjogWGLKYH7bh5TZVH2GQ8b/eb8S2jpjNc0dnzDGvwGeHZdxuAdU8O1z9aj7ZBYjccgCAe397UFL92qflVJebanCU77v3Yu8EFIDxbfwuR+fpg+BOOffU/77GHlznbhb0XcHa9QyI8Cj+riQHvRf3D3t/dBTaZF7OxynPkB4awJ5qfAa5XS9GLZmwZh2YBB2qWePwvIPWiVJT0snOEPq4W16KJ3Pszy43opeanUoNrd9prbea4sgwcROJ+F8UHDOPbtR8SGgcqY7MoM315Fhes9Dyl7QqykckmH83GV+6uY953slrMOq7asLfCbfgB4j4zv448IcPmYxa6Fys8w+TBM44d+xhjvyAF6P7IZJqDekDoc8lqQK08d6OoI888p86nIXzL3QgFbJnwRAMBue/+hYfoegU1/WXY7vNo4xvZtH8IFAs+c=
