dist: trusty
language: node_js
node_js:
- '10.9'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    sonarcloud:
      organization: sytw2019
    token:
      secure: "ORXvX1ORDZsS5HAis8zJyEYTWSlZ4rg+T5bLnjmiQ14UctiifluVBCz55QhCA4XnaP3dM/UsHM3FojA9vQ2HIWDf5SL4v7BCjRbbKuZUSl/S5H/WEZ4yE/5+c1/967cl094cLwHqmVbdKrWvT6rXXN3dqW5veGC0Cp6D1OdVTrE3/THsmE8SMkhIm6xylDPvnrxzi3660Teid6S4gZIZgkRDdO0dUcFoUJ9alaD7DysqqkX/kT9ez4Gb6IXieTDrjIquciIaWGcoPDPLiONjackubNmLyuNqcL0lcTvFsJGLgfevBql22Nx7EZxyAaacUz0jVewHbZW2s+yN0jD3OBFhz9J4FcLJ5q5Y04nmStCI5kb2IRBNyf9jiH2uUgwm0coatxlYcWp0srSCGd+z7LyxQiVntaKSk+wIYgPCfVWZbRi5WxGPhZvHpWeXrsg0cdSjCR7wJY/qyY4SnNBFp8XwgYv7gWKRLJpdzYDgOuLLx4LXNZqr8t0wWATCd7kwiDGW0yhN/Tf2qgdJBg+PcNgPckU8XJ9ncjsygXBvZSgiNVWyy0DkEA2KWBQPtwgPB3nwdP4lWIAor5eHoPvoLQzKiJIxOao2uvqD3JouQBeJhsk9WWvmwGwx2uydAfRHMhk00eqoFEMeddb160kQkeQwF4iyaM96r1AFFxacb6w="
cache:
  directories:
  - "./tiendaOnlineLogMen/node_modules"
before_install: 
- cd tiendaOnlineLogMen
- wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
- unzip sonar-scanner-cli-3.3.0.1492-linux.zip -d /tmp
  #script:
   # /tmp/sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner -Dsonar.projectKey=$SONARQUBE_PROJECT_KEY -Dsonar.sources=. -Dsonar.host.url=$SONARQUBE_URL -Dsonar.login=$SONARQUBE_LOGIN
install:
- npm install
notifications:
  slack: sytw:eFSSfJ93dL6SYCHkgOxiacNL
cure: V3XV10zQLE461U80uatOzqoXGZj+AJVlbcMI+eC509HXUOsW1BhB7GjpLUfJAm8lcmmqfc2+sx8rfCUEy7aOonbWPuwGjK4KJyjiXKNZ38S9kJadlhmKkmHFTWS9dE1Yno78DJkrgW+bSML7PQuUOnvKKD6OEFNZoQwk24ffT60OjR6Em4Wfb9EmridTkFdXGjTrKr+Lanu+sKSTsgBXTD3hX54MMfFNYmLSIVaXI0T0UoXzlSYqVks7iIILwte5yJxFA4FQauUatRZpVcm/KIfR0Bl+kyxvafviLI7thdT+uVLznb3lbc3zD5oNiotegWJfusyBzzsJhS5ZFLBJ3rQPUJPX/QXAH57nIZruvBk/YWltMK+K1gyh6C3oqL0MNVOT2wXuezbOjicVhb0oVqPu5nkkS4fc3/k92TpVNeJc1vQ4RASKxmn1okw0bINf+tp683nYWFdkYaQwpFF/2d9G4zag1TnrT5xddeU8AWAPI1jBhi/ptz1g1cCdKIwv+ZAvd3YhMo1RSuOJwyTCEPA0wb/FEQBbpQzl9/5SUnIoIWZi2cekx0+H+4vA7GlG1g4ZxQ0hrE3KL33syNi9vTRRG60WSaAaY38qQCM2SlS/wxLQAllKAUJRTsWcz2tc1G+SDk2L/HJaWSOu6a8V6ejjHePZI3e8cwP+i8k9HdY=

script:
- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
- unset CI npm run build
- cd ..
- /tmp/sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner 

