dist: trusty
language: node_js
node_js:
- '10.9'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    sonarcloud:
      organization: sytw2019
    token:
      secure: iL18P5sNdWr+Y9KIPotdKiPx5u7hxB3vPp7gQVYLRJcWhj/zlg83AvqvBM0kQyYHI627ertR3HG45jO6pCJ6kuiE3ZilaOzWn/d4/sGZq8cCjko+2GDb/lL/dU3E6jVZ6eSJWf0znAZH6IxLxypj1mqwijaz/Z4WJwSrCVsq5vBlxySmItQOSi0+5Ja7cypSpSdhPwnBXIuxsBaLPn+qDOfRd9jX6/Z/OOvkHesBU6gmMddfMLJc5MeDn2ChQ9a5SPejXunKpWHOdHwW3GNigWbjTHKBkmfBSS5SXuQhTZlr4UkXKcjL7U4288p6AbjETBgsBv3oaVgA+hmBVLYyLYKmIEf2hXPxN8yR4uI6Lwp9eawCzMtkUVdPhK4MnTV9T8aGsBItHfTaojUzAmIcvABNC4hQDR5sGzJFTCjnVNDK4MCPcO2pk3XyNEE/0JYoACfFAUoqFAOxzDAxt6RoBhNj/+IwLriM8YF+hBR8o+T/j9KqicGyhhOPYxwrpB9dA+vBVzrMtz6dZ1h6Ff7k9/YF903wA5F3RxeR73x+DOxAfqn+vUOBID13t9/uEYZDDqCyqHl2ESpipE+0UyvkuF75fgFqLYw4v6/qSZ0/koaAv0aZ5+FGVs6V+vBnZI0iQRga60Z/ygp66DxJUWXj9Wk32QVbdA421RauKO5TZLU=
cache:
  directories:
  - "./tiendaOnlineLogMen/node_modules"
before_install:
- cd tiendaOnlineLogMen
install:
- npm install
notifications:
  slack: sytw:eFSSfJ93dL6SYCHkgOxiacNL
script:
- wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.1.0.1829-linux.zip
- unzip sonar-scanner-cli-4.1.0.1829-linux.zip
- export PATH="sonar-scanner-4.1.0.1829-linux/bin:$PATH"
- cd ..
- sonar-scanner -X -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.projectKey=SyTW2019_E11
- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
env:
  secure: iL18P5sNdWr+Y9KIPotdKiPx5u7hxB3vPp7gQVYLRJcWhj/zlg83AvqvBM0kQyYHI627ertR3HG45jO6pCJ6kuiE3ZilaOzWn/d4/sGZq8cCjko+2GDb/lL/dU3E6jVZ6eSJWf0znAZH6IxLxypj1mqwijaz/Z4WJwSrCVsq5vBlxySmItQOSi0+5Ja7cypSpSdhPwnBXIuxsBaLPn+qDOfRd9jX6/Z/OOvkHesBU6gmMddfMLJc5MeDn2ChQ9a5SPejXunKpWHOdHwW3GNigWbjTHKBkmfBSS5SXuQhTZlr4UkXKcjL7U4288p6AbjETBgsBv3oaVgA+hmBVLYyLYKmIEf2hXPxN8yR4uI6Lwp9eawCzMtkUVdPhK4MnTV9T8aGsBItHfTaojUzAmIcvABNC4hQDR5sGzJFTCjnVNDK4MCPcO2pk3XyNEE/0JYoACfFAUoqFAOxzDAxt6RoBhNj/+IwLriM8YF+hBR8o+T/j9KqicGyhhOPYxwrpB9dA+vBVzrMtz6dZ1h6Ff7k9/YF903wA5F3RxeR73x+DOxAfqn+vUOBID13t9/uEYZDDqCyqHl2ESpipE+0UyvkuF75fgFqLYw4v6/qSZ0/koaAv0aZ5+FGVs6V+vBnZI0iQRga60Z/ygp66DxJUWXj9Wk32QVbdA421RauKO5TZLU=
