dist: trusty
language: node_js
node_js:
- '10.9'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sonarcloud:
    organization: "sytw2019"
    token:
      secure: "x+/EwhfihksOVgEQhDf0WQgYcqp6k8Q+zOy4F0cZExjVfNmM/2x5T6s7ziKcAm+XF0oC5mrpu4sIVPqJrFnk2Z47TNkPy2+CU4/FiyWSswrx9Bfe9I00WQJea8IX5ATvgfr997d3xTSIIEtgtnq93JSVq10Vfd3oh6u9Rw3SJksCdbgWdy23vfI6kg3ag5/DVyVh8ulGVpEZRE7cfYZH9kgA0iMHBLGFnGilgK1xqvu9eQFUdR80I45sEK9UBpVyukBhxa0Cj3mX1765RK7BX+JdrQsBJSprVjbxaxnrSWPdLNsHHN34wQu79FNcLJDLfuJa58XLwNDBlM9ZslxhAw3JJb799L+YMY4JMxL1bQ3WkdSi72XqVbOhs5PeZdcSxoOBzQoEG8OPEmTuJOS2U+2rbSMtQvU2ON3oiXle56LWafNHM4jiIC6hdp/d0zl8r2TSJydDm07+CEZSkj93d1O1f7vRV6UP9SC3FEhjQh/cmLlOzi0WR0nbeyUbyZSj3WQJ+Z7WquhFeYAGibn3+qWyoT/2tml1f/CmTxNrOohVFjUE2il8YfbRFmvv7fqoNo57Eei5c2vpxcUybaGtTBpZK5A9JBZ5Kxwg4epEDtcnzyM68lhdKVBCBs3DWPYmo+fbND1os92S7+fs0klu0Zq/wrcv8IAs7dO+Ps5gQLU="
cache:
  directories:
  - "./tiendaOnlineLogMen/node_modules"
#before_install:
#- cd tiendaOnlineLogMen
install:
- npm install
notifications:
  slack: sytw:eFSSfJ93dL6SYCHkgOxiacNL
script:
#- wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.1.0.1829-linux.zip
#- unzip sonar-scanner-cli-4.1.0.1829-linux.zip
#- export PATH="sonar-scanner-4.1.0.1829-linux/bin:$PATH"
#- cd ..
- sonar-scanner
#- cd tiendaOnlineLogMen
#- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
