dist: trusty
language: node_js
node_js:
- '10.9'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    sonarcloud:
      organization: sytw2019
    token:
      secure: HARf3CYI1aaFXUVISy+oJnvL7z68FvTA1Huyj8b8AFi/obRqe6uf202XTjeYOr0nYJkQubiorvSluFU1WKey57DHOcNho5buNL+k/mzbOBoiHJvuETQF0CS8LvGY1sljZKLyDNyRtGgaOJpKxhMZmpiKXIXmZ7WE+rKMOMMn7nkaSn0eLtS3BIIk8dJBxHR1Ovy0n0q+FzKOBC0aXQCGGt++M1njT2r6kvhN2Inefzq1ijzhcYO5jJnxtrBeAR1Xv4F8d8pz9BEBuLUmwm80hNLdueN2qqzAgOCedwS/Lh+tMEp5EL1O9QrAuCCKUrjQoGrX1un6Pnk4bzV2RqJ81HrKmBeu3A/z3MvJz7vhWocFeZAD3v5vJht8qx1iIh3gNtUE6EXt+GPR17kAyJpagNQJTVWmmsGlsAy4AQu/5UWC4CNBqKYZCOA5IYUzs0RB03+Ik9Yka/P0XV22Kz/Ij8s66tJM6cSZ1nWwDT+ZhhCxOGap2LiCd1znz3Hgm3GB5CEGvbT4C2FV7PgOr1kYHqXA10AMXnsmyJSmtWcjwAXfuBPAemtfMcQ3G6hFuPC/84TdnCfvgqcQCnTYYNKc8QfeLdkakKj9stFNHrRP2cLVRhaP+Zn/qsZDod9Hw3eqlPTnd1A01Vauh4D81BbvEXhQgOgItrtw6esJyXqEMJU=
cache:
  directories:
  - "./tiendaOnlineLogMen/node_modules"
before_install:
- cd tiendaOnlineLogMen
install:
- npm install
notifications:
  slack: sytw:eFSSfJ93dL6SYCHkgOxiacNL
script:
- wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.1.0.1829-linux.zip
- unzip sonar-scanner-cli-4.1.0.1829-linux.zip
- export PATH="sonar-scanner-4.1.0.1829-linux/bin:$PATH"
- cd ..
- sonar-scanner -X -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.projectKey=SyTW2019_E11
- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
env:
  secure: HARf3CYI1aaFXUVISy+oJnvL7z68FvTA1Huyj8b8AFi/obRqe6uf202XTjeYOr0nYJkQubiorvSluFU1WKey57DHOcNho5buNL+k/mzbOBoiHJvuETQF0CS8LvGY1sljZKLyDNyRtGgaOJpKxhMZmpiKXIXmZ7WE+rKMOMMn7nkaSn0eLtS3BIIk8dJBxHR1Ovy0n0q+FzKOBC0aXQCGGt++M1njT2r6kvhN2Inefzq1ijzhcYO5jJnxtrBeAR1Xv4F8d8pz9BEBuLUmwm80hNLdueN2qqzAgOCedwS/Lh+tMEp5EL1O9QrAuCCKUrjQoGrX1un6Pnk4bzV2RqJ81HrKmBeu3A/z3MvJz7vhWocFeZAD3v5vJht8qx1iIh3gNtUE6EXt+GPR17kAyJpagNQJTVWmmsGlsAy4AQu/5UWC4CNBqKYZCOA5IYUzs0RB03+Ik9Yka/P0XV22Kz/Ij8s66tJM6cSZ1nWwDT+ZhhCxOGap2LiCd1znz3Hgm3GB5CEGvbT4C2FV7PgOr1kYHqXA10AMXnsmyJSmtWcjwAXfuBPAemtfMcQ3G6hFuPC/84TdnCfvgqcQCnTYYNKc8QfeLdkakKj9stFNHrRP2cLVRhaP+Zn/qsZDod9Hw3eqlPTnd1A01Vauh4D81BbvEXhQgOgItrtw6esJyXqEMJU=
